name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Si ya pusiste sonar-project.properties en la raíz no necesitas estos args.
          # Si no pusiste el archivo, reemplaza YOUR_ORG / YOUR_PROJECT_KEY por lo que viste en SonarCloud.
          args: >
            -Dsonar.organization=YOUR_ORG
            -Dsonar.projectKey=YOUR_PROJECT_KEY
            -Dsonar.sources=.
